[package]
name = "sokoban-level-generator"
version = "0.0.0-development"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "level_generation"
harness = false
